# -*- coding: utf-8 -*-
"""Untitled66.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bbrb4-vC8IhqjYOeYX_gozpISiXIKUl1
"""

# ============================================================
# LAB 1 — RECONSTRUCT A SYNTHETIC PATIENT'S DATA JOURNEY
# Google Colab — SINGLE CELL VERSION
# ============================================================

# -----------------------------
# 0. SETUP
# -----------------------------
from pathlib import Path
import json
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display

DATA = Path("healthcare_ecosystem_lab_data")
DATA.mkdir(exist_ok=True)

pd.set_option("display.max_columns", 20)

print("Teaching files:", DATA.resolve())


# ============================================================
# 1. CREATE SYNTHETIC HEALTHCARE DATA
# ============================================================

patients = pd.DataFrame([
    ("P001", 1980),
    ("P002", 1992),
    ("P003", 1975),
    ("P004", 2000)
], columns=["patient_id", "birth_year"])


encounters = pd.DataFrame([
    ("E001", "P001", "2026-01-10T09:00:00+05:30", "outpatient"),
    ("E002", "P001", "2026-02-10T10:00:00+05:30", "outpatient"),
    ("E003", "P002", "2026-01-15T11:00:00+05:30", "outpatient"),
    ("E004", "P003", "2026-01-20T09:00:00+05:30", "outpatient"),
    ("E005", "P003", "2026-03-01T09:00:00+05:30", "outpatient"),
    ("E006", "P004", "2025-12-20T09:00:00+05:30", "outpatient")
], columns=["encounter_id", "patient_id", "start", "type"])


observations = pd.DataFrame([
    ("O001", "E001", "heart_rate", 78, "beats/min", "2026-01-10T09:10:00+05:30"),
    ("O001", "E001", "heart_rate", 78, "beats/min", "2026-01-10T09:10:00+05:30"),
    ("O002", "E001", "temperature", 37, "Cel", "2026-01-10T09:12:00+05:30"),
    ("O003", "E002", "heart_rate", None, "beats/min", "2026-02-10T10:10:00+05:30"),
    ("O004", "E003", "temperature", 98.6, "[degF]", "2026-01-15T11:10:00+05:30"),
    ("O005", "E004", "heart_rate", 84, "beats/min", "2026-01-20T09:10:00+05:30"),
    ("O006", "E005", "heart_rate", 80, "beats/min", "2026-03-01T09:10:00+05:30")
], columns=[
    "observation_id",
    "encounter_id",
    "code",
    "value",
    "unit",
    "effective_time"
])


notes = pd.DataFrame([
    ("N001", "P001", "E001",
     "No history of diabetes. Patient reports reduced activity."),
    ("N002", "P001", "E002",
     "Follow-up visit. Further assessment planned."),
    ("N003", "P002", "E003",
     "Family history of diabetes; patient history not established.")
], columns=[
    "note_id",
    "patient_id",
    "encounter_id",
    "text"
])


# Wearable data
times = pd.date_range(
    "2026-01-10T00:00:00+05:30",
    periods=24,
    freq="h"
)

wearable = pd.DataFrame({
    "patient_id": "P001",
    "time": times,
    "steps": [
        0, 0, 0, 0, 0, 20,
        100, 250, 300, 150, 80, 120,
        200, 180, 90, 140, 220, 400,
        350, 200, 100, 40, 10, 0
    ]
})

# Deliberately remove six hourly samples.
# A gap is NOT equivalent to zero activity.
wearable = wearable.drop(index=range(12, 18)).reset_index(drop=True)


# Save CSV files
for name, frame in {
    "patients": patients,
    "encounters": encounters,
    "observations": observations,
    "notes": notes,
    "wearable": wearable
}.items():
    frame.to_csv(DATA / f"{name}.csv", index=False)


# ============================================================
# 2. CREATE SMALL FHIR R4-STYLE BUNDLE
# ============================================================

resources = [
    {
        "resourceType": "Patient",
        "id": p
    }
    for p in patients.patient_id
]

for row in encounters.itertuples():
    resources.append({
        "resourceType": "Encounter",
        "id": row.encounter_id,
        "status": "finished",
        "class": {
            "system": "http://terminology.hl7.org/CodeSystem/v3-ActCode",
            "code": "AMB"
        },
        "subject": {
            "reference": f"Patient/{row.patient_id}"
        },
        "period": {
            "start": row.start
        }
    })


# Only two observations are placed into the FHIR bundle.
for oid, pid, eid, value, time in [
    ("O001", "P001", "E001", 78,
     "2026-01-10T09:10:00+05:30"),

    ("O005", "P003", "E004", 84,
     "2026-01-20T09:10:00+05:30")
]:
    resources.append({
        "resourceType": "Observation",
        "id": oid,
        "status": "final",
        "code": {
            "coding": [{
                "system": "http://loinc.org",
                "code": "8867-4",
                "display": "Heart rate"
            }]
        },
        "subject": {
            "reference": f"Patient/{pid}"
        },
        "encounter": {
            "reference": f"Encounter/{eid}"
        },
        "effectiveDateTime": time,
        "valueQuantity": {
            "value": value,
            "unit": "beats/minute",
            "system": "http://unitsofmeasure.org",
            "code": "/min"
        }
    })


bundle = {
    "resourceType": "Bundle",
    "type": "collection",
    "entry": [
        {
            "fullUrl":
                f"https://example.org/fhir/"
                f"{r['resourceType']}/{r['id']}",
            "resource": r
        }
        for r in resources
    ]
}

(DATA / "patient_bundle.json").write_text(
    json.dumps(bundle, indent=2),
    encoding="utf-8"
)

print("\nCreated five CSV files and one JSON file.")


# ============================================================
# 3. INVENTORY
# ============================================================

print("\n" + "=" * 70)
print("3. INVENTORY")
print("=" * 70)

tables = {
    name: pd.read_csv(DATA / f"{name}.csv")
    for name in [
        "patients",
        "encounters",
        "observations",
        "notes",
        "wearable"
    ]
}

for name, frame in tables.items():
    print(f"\n{name.upper()}")
    print("Shape:", frame.shape)
    display(frame.head(5))


patients = tables["patients"]
encounters = tables["encounters"]
observations = tables["observations"]
notes = tables["notes"]
wearable = tables["wearable"]


# Convert timestamps
encounters["start"] = pd.to_datetime(
    encounters["start"],
    utc=True
)

observations["effective_time"] = pd.to_datetime(
    observations["effective_time"],
    utc=True
)

wearable["time"] = pd.to_datetime(
    wearable["time"],
    utc=True
)


# ============================================================
# 4. DATA DICTIONARY
# ============================================================

print("\n" + "=" * 70)
print("4. DATA DICTIONARY")
print("=" * 70)

data_dictionary = pd.DataFrame([
    {
        "file": "patients",
        "column": "patient_id",
        "meaning": "Synthetic patient identifier",
        "type": "string",
        "unit": "",
        "key_role": "Primary key",
        "missing_meaning": "Should not be missing"
    },
    {
        "file": "patients",
        "column": "birth_year",
        "meaning": "Year of birth",
        "type": "integer",
        "unit": "year",
        "key_role": "Attribute",
        "missing_meaning": "Birth year unavailable"
    },
    {
        "file": "encounters",
        "column": "encounter_id",
        "meaning": "Synthetic encounter/visit identifier",
        "type": "string",
        "unit": "",
        "key_role": "Primary key",
        "missing_meaning": "Should not be missing"
    },
    {
        "file": "encounters",
        "column": "patient_id",
        "meaning": "Patient associated with encounter",
        "type": "string",
        "unit": "",
        "key_role": "Foreign key",
        "missing_meaning": "Patient reference unavailable"
    },
    {
        "file": "observations",
        "column": "observation_id",
        "meaning": "Observation identifier",
        "type": "string",
        "unit": "",
        "key_role": "Primary key",
        "missing_meaning": "Should not be missing"
    },
    {
        "file": "observations",
        "column": "code",
        "meaning": "Type of measurement",
        "type": "string",
        "unit": "",
        "key_role": "Attribute",
        "missing_meaning": "Measurement type unavailable"
    },
    {
        "file": "observations",
        "column": "value",
        "meaning": "Recorded measurement value",
        "type": "numeric",
        "unit": "Depends on unit column",
        "key_role": "Attribute",
        "missing_meaning": "Measurement value not recorded"
    },
    {
        "file": "observations",
        "column": "unit",
        "meaning": "Unit of measurement",
        "type": "string",
        "unit": "",
        "key_role": "Attribute",
        "missing_meaning": "Unit unavailable"
    },
    {
        "file": "observations",
        "column": "effective_time",
        "meaning": "Time at which observation was recorded",
        "type": "datetime",
        "unit": "timestamp",
        "key_role": "Temporal attribute",
        "missing_meaning": "Measurement time unavailable"
    },
    {
        "file": "notes",
        "column": "note_id",
        "meaning": "Clinical note identifier",
        "type": "string",
        "unit": "",
        "key_role": "Primary key",
        "missing_meaning": "Should not be missing"
    },
    {
        "file": "notes",
        "column": "text",
        "meaning": "Free-text note",
        "type": "string",
        "unit": "",
        "key_role": "Unstructured attribute",
        "missing_meaning": "No note text"
    },
    {
        "file": "wearable",
        "column": "steps",
        "meaning": "Steps in hourly interval",
        "type": "integer",
        "unit": "steps",
        "key_role": "Measurement",
        "missing_meaning": "Sample not supplied"
    }
])

display(data_dictionary)


# ============================================================
# 5. DATA QUALITY AUDIT
# ============================================================

print("\n" + "=" * 70)
print("5. DATA QUALITY AUDIT")
print("=" * 70)

print(
    "Exact duplicate observation rows:",
    observations.duplicated().sum()
)

print(
    "Repeated observation IDs:",
    observations.observation_id.duplicated().sum()
)

print("\nMissing values:")
display(
    observations.isna()
    .sum()
    .rename("missing_count")
    .to_frame()
)

print("\nMeasurement units:")
display(
    observations
    .groupby(["code", "unit"])
    .size()
    .rename("rows")
    .reset_index()
)

print("\nNotes containing keyword 'diabetes':")

notes_keyword = notes.assign(
    keyword_diabetes=notes.text.str.contains(
        "diabetes",
        case=False
    )
)

display(notes_keyword)


# ============================================================
# 6. TEMPERATURE NORMALIZATION
# ============================================================

print("\n" + "=" * 70)
print("6. TEMPERATURE NORMALIZATION")
print("=" * 70)

# Remove exact duplicate rows only.
clean_obs = observations.drop_duplicates().copy()

temperature_answer = clean_obs.loc[
    clean_obs.code.eq("temperature")
].copy()

temperature_answer["value_celsius"] = temperature_answer.apply(
    lambda r:
        (r.value - 32) * 5 / 9
        if r.unit == "[degF]"
        else r.value,
    axis=1
)

print("Temperature records:")
display(temperature_answer)


# ============================================================
# 7. LINK PATIENTS -> ENCOUNTERS -> OBSERVATIONS
# ============================================================

print("\n" + "=" * 70)
print("7. RECORD LINKAGE")
print("=" * 70)

# Attach each encounter to a patient
encounter_patient = encounters.merge(
    patients,
    on="patient_id",
    how="left",
    validate="many_to_one",
    indicator=True
)

assert encounter_patient["_merge"].eq("both").all()

encounter_patient = encounter_patient.drop(
    columns="_merge"
)


# Attach observations to encounters/patients
linked = clean_obs.merge(
    encounter_patient,
    on="encounter_id",
    how="left",
    validate="many_to_one",
    indicator=True
)

assert linked["_merge"].eq("both").all()
assert len(linked) == len(clean_obs)

linked = linked.drop(columns="_merge")

print("\nLinked observations:")
display(linked)

print(
    "Rows:",
    len(linked),
    "Distinct patients:",
    linked.patient_id.nunique()
)


# ============================================================
# 8. DEMONSTRATE BAD JOIN
# ============================================================

print("\n" + "=" * 70)
print("8. BAD JOIN DEMONSTRATION")
print("=" * 70)

bad_join = encounters.merge(
    notes[["patient_id", "note_id"]],
    on="patient_id",
    how="left"
)

print(
    "Joining notes only by patient_id causes combinations "
    "between multiple encounters and notes:"
)

display(
    bad_join.loc[
        bad_join.patient_id.eq("P001"),
        ["patient_id", "encounter_id", "note_id"]
    ]
)


# Correct join using encounter_id
correct_notes_answer = encounters.merge(
    notes[
        ["encounter_id", "note_id", "text"]
    ],
    on="encounter_id",
    how="left",
    validate="one_to_many"
)

print("\nCorrect encounter-level note join:")
display(correct_notes_answer)

assert len(
    correct_notes_answer.loc[
        correct_notes_answer.patient_id.eq("P001")
    ]
) == 2


# ============================================================
# 9. COHORT CONSTRUCTION
# ============================================================

print("\n" + "=" * 70)
print("9. COHORT CONSTRUCTION")
print("=" * 70)

# Cohort rule:
# Include patients with at least two DISTINCT encounters
# starting in [2026-01-01, 2026-03-01)
# using Asia/Kolkata local time.

window_start = pd.Timestamp(
    "2026-01-01",
    tz="Asia/Kolkata"
).tz_convert("UTC")

window_end = pd.Timestamp(
    "2026-03-01",
    tz="Asia/Kolkata"
).tz_convert("UTC")


eligible_encounters = encounters.loc[
    encounters.start.ge(window_start)
    &
    encounters.start.lt(window_end)
].copy()


counts = (
    eligible_encounters
    .groupby("patient_id")
    .encounter_id
    .nunique()
)

cohort = (
    counts[counts.ge(2)]
    .rename("encounter_count")
    .reset_index()
)

print("Eligible encounters:")
display(eligible_encounters)

print("\nFinal cohort:")
display(cohort)

print(
    "\nIncluded patient IDs:",
    cohort.patient_id.tolist()
)


# ============================================================
# 10. WHY P003 IS EXCLUDED
# ============================================================

print("\nP003 encounters:")

display(
    encounters.loc[
        encounters.patient_id.eq("P003"),
        ["encounter_id", "start"]
    ]
)

print(
    "\nP003 is excluded because its second encounter is exactly "
    "on 1 March 2026, which is the EXCLUDED end boundary."
)


# ============================================================
# 11. READ FHIR JSON
# ============================================================

print("\n" + "=" * 70)
print("11. FHIR JSON PARSING")
print("=" * 70)

bundle_loaded = json.loads(
    (DATA / "patient_bundle.json")
    .read_text(encoding="utf-8")
)

resource_index = {
    f"{entry['resource']['resourceType']}/"
    f"{entry['resource']['id']}":
        entry["resource"]
    for entry in bundle_loaded["entry"]
}


fhir_rows = []

for resource in resource_index.values():

    if resource["resourceType"] != "Observation":
        continue

    patient_ref = resource["subject"]["reference"]
    encounter_ref = resource["encounter"]["reference"]

    assert patient_ref in resource_index
    assert encounter_ref in resource_index

    assert (
        resource_index[encounter_ref]["subject"]["reference"]
        == patient_ref
    )

    coding = next(
        c
        for c in resource["code"]["coding"]
        if c["system"] == "http://loinc.org"
    )

    q = resource["valueQuantity"]

    fhir_rows.append({
        "observation_id": resource["id"],
        "patient_id": patient_ref.split("/")[-1],
        "encounter_id": encounter_ref.split("/")[-1],
        "loinc_code": coding["code"],
        "value": q["value"],
        "ucum_code": q["code"],
        "effective_time":
            resource["effectiveDateTime"]
    })


fhir_frame = pd.DataFrame(fhir_rows)

fhir_frame["effective_time"] = pd.to_datetime(
    fhir_frame["effective_time"],
    utc=True
)

print("FHIR observations:")
display(fhir_frame)


# ============================================================
# 12. COMPARE FHIR WITH CSV
# ============================================================

print("\n" + "=" * 70)
print("12. FHIR vs CSV COMPARISON")
print("=" * 70)

comparison_source = linked.copy()

comparison_source["loinc_code"] = (
    comparison_source.code.map({
        "heart_rate": "8867-4"
    })
)

comparison_source["ucum_code"] = (
    comparison_source.unit.map({
        "beats/min": "/min"
    })
)


comparison = fhir_frame.merge(
    comparison_source,
    on="observation_id",
    how="left",
    suffixes=("_fhir", "_csv"),
    validate="one_to_one",
    indicator=True
)

assert comparison["_merge"].eq("both").all()


for field in [
    "patient_id",
    "encounter_id",
    "loinc_code",
    "value",
    "ucum_code",
    "effective_time"
]:
    assert comparison[
        f"{field}_fhir"
    ].eq(
        comparison[f"{field}_csv"]
    ).all(), field


display(comparison)

print(
    "All two FHIR observations agree with their CSV counterparts "
    "on identity, code, value, unit, and time."
)

print(
    "\nFHIR contains fewer observations than CSV because the "
    "synthetic FHIR bundle intentionally contains only two observations."
)


# ============================================================
# 13. VISUALIZE PATIENT JOURNEY
# ============================================================

print("\n" + "=" * 70)
print("13. PATIENT JOURNEY VISUALIZATION")
print("=" * 70)

p1_encounters = encounters.loc[
    encounters.patient_id.eq("P001")
]

p1_obs = linked.loc[
    linked.patient_id.eq("P001")
]


fig, ax = plt.subplots(figsize=(12, 4))

ax.scatter(
    p1_encounters.start.dt.tz_convert("Asia/Kolkata"),
    [1] * len(p1_encounters),
    label="Encounter",
    marker="s"
)

ax.scatter(
    p1_obs.effective_time.dt.tz_convert("Asia/Kolkata"),
    [0] * len(p1_obs),
    label="Observation record",
    marker="x"
)

ax.set_yticks(
    [0, 1],
    ["Observation", "Encounter"]
)

ax.set_title(
    "P001: Recorded Healthcare Events"
)

ax.legend(
    loc="upper center"
)

fig.autofmt_xdate()

plt.tight_layout()
plt.show()


# ============================================================
# 14. WEARABLE DATA — MISSING SAMPLES
# ============================================================

print("\n" + "=" * 70)
print("14. WEARABLE DATA AND MISSING SAMPLES")
print("=" * 70)

expected = pd.date_range(
    "2026-01-10",
    periods=24,
    freq="h",
    tz="Asia/Kolkata"
)

series = (
    wearable
    .set_index("time")["steps"]
    .tz_convert("Asia/Kolkata")
    .reindex(expected)
)


fig, ax = plt.subplots(figsize=(12, 4))

ax.plot(
    series.index.hour,
    series.values,
    marker="o"
)

ax.axvspan(
    11.5,
    17.5,
    alpha=0.15,
    label="No samples supplied"
)

ax.set(
    xlabel="Hour (Asia/Kolkata)",
    ylabel="Steps in hourly interval",
    title="Synthetic Wearable Activity — Gaps Remain Missing"
)

ax.legend()

plt.tight_layout()
plt.show()


print(
    "Missing expected hourly samples:",
    series.isna().sum()
)


# ============================================================
# 15. FINAL QUALITY SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("15. FINAL QUALITY SUMMARY")
print("=" * 70)

quality_summary = pd.DataFrame([
    {
        "Issue": "Exact duplicate observation",
        "Evidence": "One identical observation row appears twice",
        "Count": observations.duplicated().sum()
    },
    {
        "Issue": "Missing measurement",
        "Evidence": "O003 has no numeric value",
        "Count": observations.value.isna().sum()
    },
    {
        "Issue": "Mixed temperature units",
        "Evidence": "Cel and [degF]",
        "Count": observations.loc[
            observations.code.eq("temperature"),
            "unit"
        ].nunique()
    },
    {
        "Issue": "Wearable sample gap",
        "Evidence": "Expected hourly timestamps are absent",
        "Count": series.isna().sum()
    }
])

display(quality_summary)


# ============================================================
# 16. FINAL REFLECTION — PRINT ANSWERS
# ============================================================

print("\n" + "=" * 70)
print("16. FINAL REFLECTION")
print("=" * 70)

reflection = """
1. What information was lost when FHIR observations were flattened?

Flattening retained selected fields such as observation ID, patient ID,
encounter ID, LOINC code, value, UCUM code, and effective time. However,
the original FHIR resource also contained resource type, status, fullUrl,
coding-system details, display labels, reference structure, and other
resource context. These details are not represented in the flattened
analysis table.

2. Which limitations matter before training a model?

Important limitations include duplicate records, missing measurements,
inconsistent measurement units, incomplete FHIR extraction, sparse
wearable data, and unstructured clinical notes. The dataset is also
synthetic and very small, so it should not be used to evaluate clinical
performance or disease prevalence.

3. If predicting at encounter start, would measurements recorded ten
minutes later be available?

Not necessarily. A measurement's event/effective time can differ from
the time at which the data became available to a prediction system.
For a real prediction task, an availability timestamp or ingestion time
would help determine whether a feature was actually available at the
prediction time.
"""

print(reflection)


# ============================================================
# 17. REFERENCE CHECKS
# ============================================================

print("\n" + "=" * 70)
print("17. REFERENCE CHECKS")
print("=" * 70)

assert cohort.patient_id.tolist() == ["P001"]
assert len(clean_obs) == 6
assert linked.patient_id.nunique() == 3
assert series.isna().sum() == 6

print("✓ Exact duplicate successfully removed")
print("✓ Patients linked correctly")
print("✓ Correct cohort: P001")
print("✓ P003 excluded because March 1 is the end boundary")
print("✓ FHIR comparison passed")
print("✓ Wearable gap detected: 6 missing samples")
print("✓ All reference checks passed")


# ============================================================
# 18. SHOW GENERATED FILES
# ============================================================

print("\n" + "=" * 70)
print("18. GENERATED FILES")
print("=" * 70)

for file in sorted(DATA.iterdir()):
    print(file.name)

print("\nLab completed successfully.")