# -*- coding: utf-8 -*-
"""Untitled67.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yd8WewXn_PECrtGip2s3tScW9LY903Az
"""

# ============================================================
# HEART DISEASE REFERRAL ALERTING
# COMPLETE CORRECTED GOOGLE COLAB CODE
# ============================================================

# ============================================================
# 0. IMPORT LIBRARIES
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    ConfusionMatrixDisplay,
    roc_curve,
    roc_auc_score,
    precision_recall_curve
)

plt.style.use("seaborn-v0_8-whitegrid")


# ============================================================
# 1. LOAD DATASET
# ============================================================

url = "https://raw.githubusercontent.com/AndreasPr/Heart-Disease-Prediction-System/master/processed.cleveland.data.csv"

columns = [
    "age",
    "sex",
    "cp",
    "trestbps",
    "chol",
    "fbs",
    "restecg",
    "thalach",
    "exang",
    "oldpeak",
    "slope",
    "ca",
    "thal",
    "target"
]

# Load dataset
# '?' is converted to NaN
df = pd.read_csv(
    url,
    names=columns,
    na_values="?"
)

# Binarize target:
# 0 = no disease
# 1-4 = disease present
df["target"] = (
    df["target"] > 0
).astype(int)

print("=" * 70)
print("1. DATASET")
print("=" * 70)

print("\nFirst 5 rows:")
display(df.head())

print("\nNumber of patients:", len(df))
print("Number of features:", df.shape[1] - 1)
print("Dataset shape:", df.shape)


# ============================================================
# 2. EXPLORATORY DATA ANALYSIS
# ============================================================

# ------------------------------------------------------------
# 2.1 MISSING VALUES
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.1 MISSING VALUES")
print("=" * 70)

print("\nMissing values before imputation:")
print(df.isnull().sum())

# Find columns containing missing values
missing_cols = df.columns[
    df.isnull().any()
].tolist()

print("\nColumns containing missing values:")
print(missing_cols)

# Impute missing values using MODE
#
# ca and thal are categorical/ordinal codes,
# so mode is more appropriate than mean.
for col in missing_cols:

    mode_value = df[col].mode()[0]

    df[col] = df[col].fillna(
        mode_value
    )

    print(
        f"{col}: missing values replaced "
        f"with mode = {mode_value}"
    )

print("\nMissing values after imputation:")
print(df.isnull().sum())

print(
    "\nTotal missing values:",
    df.isnull().sum().sum()
)

# Safety check
assert df.isnull().sum().sum() == 0, \
    "ERROR: Missing values still exist!"


# ------------------------------------------------------------
# 2.2 ENCODING CATEGORICAL FEATURES
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.2 CATEGORICAL ENCODING")
print("=" * 70)

# Nominal categorical features
nominal_cols = [
    "cp",
    "restecg",
    "slope",
    "thal"
]

# Already binary
binary_cols = [
    "sex",
    "fbs",
    "exang"
]

# Convert nominal and binary codes to integers
for col in nominal_cols + binary_cols:

    df[col] = df[col].astype(int)

# ca is a count from 0-3
df["ca"] = df["ca"].astype(int)

# One-hot encode nominal categorical variables
df_encoded = pd.get_dummies(
    df,
    columns=nominal_cols,
    drop_first=False,
    dtype=int
)

print(
    "\nOriginal number of columns:",
    df.shape[1]
)

print(
    "Encoded number of columns:",
    df_encoded.shape[1]
)

print("\nEncoded columns:")
print(df_encoded.columns.tolist())

print("\nFirst 5 encoded rows:")
display(df_encoded.head())

# IMPORTANT SAFETY CHECK
print("\nMissing values after encoding:")
print(df_encoded.isnull().sum())

print(
    "\nTotal NaN values:",
    df_encoded.isnull().sum().sum()
)

assert df_encoded.isnull().sum().sum() == 0, \
    "ERROR: NaN values still exist!"


# ------------------------------------------------------------
# 2.3 TARGET DISTRIBUTION
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.3 TARGET DISTRIBUTION")
print("=" * 70)

plt.figure(figsize=(7, 5))

sns.countplot(
    data=df_encoded,
    x="target"
)

plt.title(
    "Heart Disease Target Distribution"
)

plt.xlabel(
    "Disease Status"
)

plt.ylabel(
    "Number of Patients"
)

plt.xticks(
    [0, 1],
    ["No Disease", "Disease Present"]
)

plt.show()

class_proportions = (
    df_encoded["target"]
    .value_counts(normalize=True)
    .sort_index()
)

print("\nClass proportions:")
print(class_proportions)

print("\nClass percentages:")
print(
    (class_proportions * 100).round(2)
)


# ------------------------------------------------------------
# 2.4 FEATURE DISTRIBUTIONS
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.4 FEATURE DISTRIBUTIONS")
print("=" * 70)

continuous_features = [
    "age",
    "trestbps",
    "chol",
    "thalach",
    "oldpeak"
]

fig, axes = plt.subplots(
    2,
    3,
    figsize=(15, 9)
)

axes = axes.flatten()

for i, feature in enumerate(
    continuous_features
):

    sns.histplot(
        df_encoded[feature],
        kde=True,
        ax=axes[i]
    )

    axes[i].set_title(
        f"Distribution of {feature}"
    )

    axes[i].set_xlabel(feature)
    axes[i].set_ylabel("Frequency")

# Hide unused subplot
axes[-1].axis("off")

plt.tight_layout()
plt.show()


# ------------------------------------------------------------
# 2.5 OUTLIERS
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.5 OUTLIERS")
print("=" * 70)

fig, axes = plt.subplots(
    2,
    3,
    figsize=(15, 8)
)

axes = axes.flatten()

for i, feature in enumerate(
    continuous_features
):

    sns.boxplot(
        y=df_encoded[feature],
        ax=axes[i]
    )

    axes[i].set_title(
        f"Boxplot of {feature}"
    )

    axes[i].set_ylabel(feature)

axes[-1].axis("off")

plt.tight_layout()
plt.show()


# ------------------------------------------------------------
# 2.6 CORRELATION MATRIX
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2.6 CORRELATION MATRIX")
print("=" * 70)

correlation_matrix = (
    df_encoded.corr()
)

plt.figure(
    figsize=(16, 12)
)

sns.heatmap(
    correlation_matrix,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    center=0
)

plt.title(
    "Correlation Heatmap - Heart Disease Dataset"
)

plt.tight_layout()
plt.show()

target_correlations = (
    correlation_matrix["target"]
    .drop("target")
    .sort_values(
        key=abs,
        ascending=False
    )
)

print(
    "\nFeatures most strongly correlated "
    "with target:"
)

display(
    target_correlations.to_frame(
        "Correlation with Target"
    )
)


# ============================================================
# 3. DATA PREPARATION
# ============================================================

print("\n" + "=" * 70)
print("3. DATA PREPARATION")
print("=" * 70)

# Features
X = df_encoded.drop(
    "target",
    axis=1
)

# Target
y = df_encoded["target"]

print("\nX shape:", X.shape)
print("y shape:", y.shape)

# Train/test split
X_train, X_test, y_train, y_test = (
    train_test_split(
        X,
        y,
        test_size=0.20,
        stratify=y,
        random_state=42
    )
)

print(
    "\nTraining samples:",
    len(X_train)
)

print(
    "Testing samples:",
    len(X_test)
)

print("\nTraining class proportions:")
print(
    y_train.value_counts(
        normalize=True
    )
)

print("\nTesting class proportions:")
print(
    y_test.value_counts(
        normalize=True
    )
)


# ------------------------------------------------------------
# STANDARDIZATION
# ------------------------------------------------------------

scaler = StandardScaler()

# Fit ONLY on training data
X_train_scaled = scaler.fit_transform(
    X_train
)

# Transform test data
X_test_scaled = scaler.transform(
    X_test
)

print(
    "\nX_train_scaled shape:",
    X_train_scaled.shape
)

print(
    "X_test_scaled shape:",
    X_test_scaled.shape
)

# Safety checks
print(
    "\nNaN values in X_train_scaled:",
    np.isnan(X_train_scaled).sum()
)

print(
    "NaN values in X_test_scaled:",
    np.isnan(X_test_scaled).sum()
)

assert np.isnan(X_train_scaled).sum() == 0
assert np.isnan(X_test_scaled).sum() == 0


# ============================================================
# 4. LOGISTIC REGRESSION
# ============================================================

print("\n" + "=" * 70)
print("4. LOGISTIC REGRESSION")
print("=" * 70)

model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

model.fit(
    X_train_scaled,
    y_train
)

print(
    "\nLogistic Regression trained successfully!"
)


# ------------------------------------------------------------
# COEFFICIENTS
# ------------------------------------------------------------

coefficients = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_[0]
})

coefficients["Absolute Coefficient"] = (
    coefficients["Coefficient"].abs()
)

coefficients = coefficients.sort_values(
    "Coefficient",
    ascending=False
)

print("\nModel coefficients:")

display(coefficients)


# ------------------------------------------------------------
# PREDICTIONS
# ------------------------------------------------------------

y_pred = model.predict(
    X_test_scaled
)

y_pred_proba = model.predict_proba(
    X_test_scaled
)[:, 1]


# ------------------------------------------------------------
# ACCURACY
# ------------------------------------------------------------

accuracy = accuracy_score(
    y_test,
    y_pred
)

print(
    f"\nAccuracy at 0.5 threshold: "
    f"{accuracy:.4f}"
)


# ------------------------------------------------------------
# CONFUSION MATRIX
# ------------------------------------------------------------

cm = confusion_matrix(
    y_test,
    y_pred
)

print("\nConfusion Matrix:")
print(cm)

fig, ax = plt.subplots(
    figsize=(6, 5)
)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=[
        "No Disease",
        "Disease"
    ]
)

disp.plot(
    ax=ax,
    cmap="Blues",
    values_format="d"
)

plt.title(
    "Confusion Matrix - Threshold 0.5"
)

plt.show()


# ------------------------------------------------------------
# CLASSIFICATION REPORT
# ------------------------------------------------------------

print(
    "\nClassification Report - Threshold 0.5:"
)

print(
    classification_report(
        y_test,
        y_pred,
        target_names=[
            "No Disease",
            "Disease"
        ]
    )
)


# ------------------------------------------------------------
# ROC CURVE
# ------------------------------------------------------------

fpr, tpr, roc_thresholds = (
    roc_curve(
        y_test,
        y_pred_proba
    )
)

auc_score = roc_auc_score(
    y_test,
    y_pred_proba
)

print(
    f"\nROC AUC: {auc_score:.4f}"
)

plt.figure(
    figsize=(7, 6)
)

plt.plot(
    fpr,
    tpr,
    linewidth=2,
    label=f"Logistic Regression (AUC = {auc_score:.3f})"
)

plt.plot(
    [0, 1],
    [0, 1],
    linestyle="--",
    label="Random Guessing"
)

plt.xlabel(
    "False Positive Rate"
)

plt.ylabel(
    "True Positive Rate / Recall"
)

plt.title(
    "ROC Curve"
)

plt.legend()

plt.show()


# ============================================================
# 5. ALERT THRESHOLD ANALYSIS
# ============================================================

print("\n" + "=" * 70)
print("5. ALERT THRESHOLD ANALYSIS")
print("=" * 70)

# Precision-recall curve
precisions, recalls, pr_thresholds = (
    precision_recall_curve(
        y_test,
        y_pred_proba
    )
)

# Referral rate at each threshold
referral_rates = np.array([
    (y_pred_proba >= threshold).mean()
    for threshold in pr_thresholds
])


# ------------------------------------------------------------
# PLOT THRESHOLD TRADE-OFF
# ------------------------------------------------------------

fig, ax1 = plt.subplots(
    figsize=(11, 6)
)

ax1.plot(
    pr_thresholds,
    precisions[:-1],
    linewidth=2,
    label="Precision"
)

ax1.plot(
    pr_thresholds,
    recalls[:-1],
    linewidth=2,
    label="Recall / Sensitivity"
)

ax1.set_xlabel(
    "Decision Threshold"
)

ax1.set_ylabel(
    "Precision / Recall"
)

ax1.set_ylim(
    0,
    1.05
)

ax1.legend(
    loc="center left"
)

ax2 = ax1.twinx()

ax2.plot(
    pr_thresholds,
    referral_rates,
    linestyle="--",
    linewidth=2,
    label="Referral Rate"
)

ax2.set_ylabel(
    "Referral Rate"
)

ax2.set_ylim(
    0,
    1.05
)

plt.title(
    "Precision, Recall and Referral Rate vs Threshold"
)

plt.tight_layout()
plt.show()


# ------------------------------------------------------------
# THRESHOLD TABLE
# ------------------------------------------------------------

threshold_summary = pd.DataFrame({
    "Threshold": pr_thresholds,
    "Precision": precisions[:-1],
    "Recall": recalls[:-1],
    "Referral Rate": referral_rates
})

print("\nThreshold summary:")

display(threshold_summary)


# ------------------------------------------------------------
# CHOSEN THRESHOLD
# ------------------------------------------------------------

# The exercise states that a missed case has approximately
# 5x the cost of an unnecessary referral.
#
# Therefore we use a threshold below 0.5 to emphasize recall.
#
# You can change this value after examining the graph.

my_threshold = 0.35

print(
    f"\nChosen threshold = {my_threshold}"
)


# ------------------------------------------------------------
# PREDICTIONS AT CHOSEN THRESHOLD
# ------------------------------------------------------------

y_pred_threshold = (
    y_pred_proba >= my_threshold
).astype(int)


# ------------------------------------------------------------
# CONFUSION MATRIX
# ------------------------------------------------------------

cm_threshold = confusion_matrix(
    y_test,
    y_pred_threshold
)

print(
    f"\nConfusion Matrix - Threshold {my_threshold}:"
)

print(cm_threshold)

fig, ax = plt.subplots(
    figsize=(6, 5)
)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm_threshold,
    display_labels=[
        "No Disease",
        "Disease"
    ]
)

disp.plot(
    ax=ax,
    cmap="Blues",
    values_format="d"
)

plt.title(
    f"Confusion Matrix - Threshold {my_threshold}"
)

plt.show()


# ------------------------------------------------------------
# CLASSIFICATION REPORT
# ------------------------------------------------------------

print(
    f"\nClassification Report - "
    f"Threshold {my_threshold}:"
)

print(
    classification_report(
        y_test,
        y_pred_threshold,
        target_names=[
            "No Disease",
            "Disease"
        ]
    )
)


# ------------------------------------------------------------
# COMPARE DEFAULT VS CHOSEN THRESHOLD
# ------------------------------------------------------------

default_cm = confusion_matrix(
    y_test,
    y_pred
)

chosen_cm = confusion_matrix(
    y_test,
    y_pred_threshold
)

tn_default, fp_default, fn_default, tp_default = (
    default_cm.ravel()
)

tn_chosen, fp_chosen, fn_chosen, tp_chosen = (
    chosen_cm.ravel()
)

default_sensitivity = (
    tp_default /
    (tp_default + fn_default)
)

chosen_sensitivity = (
    tp_chosen /
    (tp_chosen + fn_chosen)
)

default_referral_rate = (
    y_pred.mean()
)

chosen_referral_rate = (
    y_pred_threshold.mean()
)

comparison = pd.DataFrame({
    "Metric": [
        "Threshold",
        "Sensitivity / Recall",
        "Referral Rate",
        "False Negatives",
        "False Positives",
        "True Positives",
        "True Negatives"
    ],

    "Default 0.5": [
        0.50,
        default_sensitivity,
        default_referral_rate,
        fn_default,
        fp_default,
        tp_default,
        tn_default
    ],

    "Chosen Threshold": [
        my_threshold,
        chosen_sensitivity,
        chosen_referral_rate,
        fn_chosen,
        fp_chosen,
        tp_chosen,
        tn_chosen
    ]
})

print(
    "\nDefault vs Chosen Threshold:"
)

display(comparison)


# ============================================================
# 6. THREE SAMPLE PATIENTS
# ============================================================

print("\n" + "=" * 70)
print("6. THREE SAMPLE PATIENTS")
print("=" * 70)


# ------------------------------------------------------------
# CREATE SAMPLE PATIENTS
# ------------------------------------------------------------

sample_patients = pd.DataFrame([
    {
        # Patient A: several risk factors
        "age": 62,
        "sex": 1,
        "trestbps": 152,
        "chol": 275,
        "fbs": 0,
        "thalach": 118,
        "exang": 1,
        "oldpeak": 2.4,
        "ca": 2,

        "cp_2": 0,
        "cp_3": 0,
        "cp_4": 1,

        "restecg_1": 0,
        "restecg_2": 1,

        "slope_2": 1,
        "slope_3": 0,

        "thal_6": 0,
        "thal_7": 1
    },

    {
        # Patient B: mostly low-risk factors
        "age": 41,
        "sex": 0,
        "trestbps": 118,
        "chol": 190,
        "fbs": 0,
        "thalach": 172,
        "exang": 0,
        "oldpeak": 0.2,
        "ca": 0,

        "cp_2": 1,
        "cp_3": 0,
        "cp_4": 0,

        "restecg_1": 0,
        "restecg_2": 0,

        "slope_2": 0,
        "slope_3": 0,

        "thal_6": 0,
        "thal_7": 0
    },

    {
        # Patient C: mixed / borderline signals
        "age": 55,
        "sex": 1,
        "trestbps": 130,
        "chol": 233,
        "fbs": 1,
        "thalach": 150,
        "exang": 0,
        "oldpeak": 1.0,
        "ca": 0,

        "cp_2": 0,
        "cp_3": 1,
        "cp_4": 0,

        "restecg_1": 0,
        "restecg_2": 0,

        "slope_2": 1,
        "slope_3": 0,

        "thal_6": 0,
        "thal_7": 0
    }
])


# ------------------------------------------------------------
# CRITICAL FIX
# ------------------------------------------------------------
#
# The training data contains every dummy variable generated
# by pd.get_dummies().
#
# The manually entered sample patients do not necessarily
# contain every dummy column.
#
# Reindexing with fill_value=0 makes the sample patients
# have EXACTLY the same columns as X.
#
# Missing dummy categories are represented by 0 rather than NaN.

sample_patients = sample_patients.reindex(
    columns=X.columns,
    fill_value=0
)


# ------------------------------------------------------------
# SAFETY CHECK
# ------------------------------------------------------------

print(
    "\nNumber of NaN values in sample patients:",
    sample_patients.isnull().sum().sum()
)

assert sample_patients.isnull().sum().sum() == 0, \
    "ERROR: Sample patients contain NaN values!"

print(
    "Number of features in sample patients:",
    sample_patients.shape[1]
)

print(
    "Number of features used by model:",
    X.shape[1]
)

assert sample_patients.shape[1] == X.shape[1], \
    "ERROR: Feature counts do not match!"


# ------------------------------------------------------------
# DISPLAY SAMPLE PATIENTS
# ------------------------------------------------------------

print("\nSample patients:")
display(sample_patients)


# ------------------------------------------------------------
# SCALE SAMPLE PATIENTS
# ------------------------------------------------------------

sample_patients_scaled = scaler.transform(
    sample_patients
)

print(
    "\nNaN values after scaling:",
    np.isnan(
        sample_patients_scaled
    ).sum()
)

assert np.isnan(
    sample_patients_scaled
).sum() == 0, \
    "ERROR: NaN values appeared after scaling!"


# ------------------------------------------------------------
# PREDICT PROBABILITIES
# ------------------------------------------------------------

sample_probabilities = (
    model.predict_proba(
        sample_patients_scaled
    )[:, 1]
)


# ------------------------------------------------------------
# CREATE RESULTS TABLE
# ------------------------------------------------------------

results = pd.DataFrame({

    "Patient": [
        "Patient A",
        "Patient B",
        "Patient C"
    ],

    "Predicted Probability": (
        sample_probabilities
    ),

    "Alert at 0.5": (
        sample_probabilities >= 0.5
    ),

    f"Alert at {my_threshold}": (
        sample_probabilities >= my_threshold
    )
})


# Convert True/False into readable alerts
results["Alert at 0.5"] = (
    results["Alert at 0.5"]
    .map({
        True: "REFER",
        False: "DO NOT REFER"
    })
)

results[
    f"Alert at {my_threshold}"
] = (
    results[
        f"Alert at {my_threshold}"
    ]
    .map({
        True: "REFER",
        False: "DO NOT REFER"
    })
)


# Round probabilities
results["Predicted Probability"] = (
    results["Predicted Probability"]
    .round(3)
)


# ------------------------------------------------------------
# DISPLAY RESULTS
# ------------------------------------------------------------

print(
    "\nClinical Decision Support Results:"
)

display(results)


# ------------------------------------------------------------
# CHECK FOR CHANGED ALERTS
# ------------------------------------------------------------

default_alerts = (
    sample_probabilities >= 0.5
)

chosen_alerts = (
    sample_probabilities >= my_threshold
)

changed_alerts = (
    default_alerts != chosen_alerts
)

print(
    "\nPatients whose alert changes:"
)

if changed_alerts.any():

    display(
        results.loc[
            changed_alerts
        ]
    )

else:

    print(
        "No patient's alert changes "
        "at the selected threshold."
    )


# ============================================================
# FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("LAB COMPLETE")
print("=" * 70)

print(
    f"\nDefault threshold: {0.50}"
)

print(
    f"Chosen threshold: {my_threshold}"
)

print(
    f"\nDefault sensitivity: "
    f"{default_sensitivity:.3f}"
)

print(
    f"Chosen sensitivity: "
    f"{chosen_sensitivity:.3f}"
)

print(
    f"\nDefault referral rate: "
    f"{default_referral_rate:.3f}"
)

print(
    f"Chosen referral rate: "
    f"{chosen_referral_rate:.3f}"
)

print(
    f"\nROC AUC: {auc_score:.3f}"
)

print("""
This is a teaching exercise using a small public research dataset.
The model output is not a diagnosis or a validated clinical
referral recommendation.

The threshold changes the balance between false negatives and
false positives. A lower threshold generally flags more patients,
which can increase recall while also increasing referrals.
""")